import { memo } from 'react'
import type { CharacterStyle } from '../../domain'
import { LEARNING_STAGES } from '../../game/courseConfig'
import type { AdventureAction, AdventureEvent } from '../../game/gameRunReducer'
import type { RewardDefinition } from '../../rewards'
import { Explorer, RewardVisual } from './GameVisuals'
import { UIRuby } from '../UIRuby'

export const AdventureScenes = memo(function AdventureScenes({ stageIndex, action, event, reward, trailTreasure, character, stageWalked, stepQueue, stepDelay, courseProgress, walkPercent, sentenceProgress, awaitingFinish }: { stageIndex: number; action: AdventureAction; event: AdventureEvent | null; reward: RewardDefinition | null; trailTreasure: RewardDefinition | null; character: CharacterStyle; stageWalked: number; stepQueue: number; stepDelay: number; courseProgress: number; walkPercent: number; sentenceProgress: number; awaitingFinish: boolean }) {
  const stage = LEARNING_STAGES[stageIndex]
  const journeyStatus = stepQueue >= 7 ? 'いいペースで冒険中！' : action === 'walk' ? 'ステージを てくてく…' : action === 'idle' ? 'ステージ全体の旅マップ' : '次の文へ向けて休憩中'
  return <>
    <div className={`adventure-scene course-journey panel scene-${stageIndex} ${action}`} style={{ '--step-speed': `${stepDelay}ms`, '--walk-progress': `${walkPercent}%`, backgroundImage: `url(${stage.journeyBackground})` } as React.CSSProperties} aria-label={`ステージ全体の進みぐあい ${Math.round(courseProgress * 100)}パーセント`}><div className="scene-sky"><span className="scene-cloud">☁</span><span className="scene-birds">⌁　⌁</span></div><div className="scene-hills"><i /><i /></div><div className="walking-path"><i style={{ width: `${walkPercent}%` }} /></div>{event && <div className="adventure-event journey-event">{reward ? <RewardVisual reward={reward} /> : event.asset ? <img src={event.asset} alt="" /> : <b>{event.icon}</b>}<span><UIRuby>{event.text}</UIRuby></span></div>}<div className={`adventurer ${action}`}><Explorer variant={character} key={stageWalked} /><span className="step-shadow" /></div><div className={`walk-status ${stepQueue >= 7 ? 'speed-up' : ''}`}><b><UIRuby>{journeyStatus}</UIRuby></b><span>{Math.round(courseProgress * 100)}%</span></div></div>
    <div className={`perspective-scene panel scene-${stageIndex} ${action} ${awaitingFinish ? 'sentence-arrival' : ''}`} style={{ '--depth-progress': sentenceProgress, backgroundImage: `linear-gradient(rgba(13,55,60,.05),rgba(6,35,38,.22)),url(${stage.background})`, backgroundSize: `${115 + sentenceProgress * 24}% auto` } as React.CSSProperties} aria-label={`一人称視点の道。文の進みぐあい ${Math.round(sentenceProgress * 100)}パーセント`}><div className="pov-topline"><span>👀 冒険者の視点</span><b>この文の道のり　{Math.round(sentenceProgress * 100)}%</b></div><div className="pov-horizon"><span>{stage.icon}</span></div><div className="pov-road"><i /><i /><i /><i /><i /></div><div className="pov-scenery left"><i /><i /><i /></div><div className="pov-scenery right"><i /><i /><i /></div>{trailTreasure && !awaitingFinish && <div className="trail-glow" style={{ top: `${40 + sentenceProgress * 27}%`, transform: `translate(-50%,-50%) scale(${.45 + sentenceProgress * 1.05})` }}><span>✦</span><b>なにかが光っている…</b></div>}{awaitingFinish && reward?.type === 'friend' && <div className="pov-creature-arrival"><RewardVisual reward={reward} /><b>いきものが こちらを見ている！</b></div>}{awaitingFinish && reward?.type === 'treasure' && <div className="pov-treasure-arrival"><span>✨</span><b>光るものに たどり着いた！</b></div>}<div className="pov-speed-lines"><i /><i /><i /><i /></div><div className="pov-body"><span /><span /><b>🎒</b></div></div>
  </>
})
