import { memo } from 'react'
import type { CollectionRecord } from '../../rewards'
import { FRIEND_REWARDS, TREASURE_REWARDS, getReward } from '../../rewards'
import { RewardVisual } from './GameVisuals'

export const GameSidePanel = memo(function GameSidePanel({ collection, creatureCount, treasureCount, mistakeCount, weakKey, totalKeyAttempts, accuracy, onCollection, onReview, onStats }: { collection: CollectionRecord[]; creatureCount: number; treasureCount: number; mistakeCount: number; weakKey?: { key: string; missRate: number }; totalKeyAttempts: number; accuracy: number; onCollection: (tab: 'friend' | 'treasure') => void; onReview: () => void; onStats: () => void }) {
  const friends = collection.filter((item) => item.type === 'friend')
  const treasures = collection.filter((item) => item.type === 'treasure')
  return <aside className="side-panel"><button className="friends-card panel collection-preview-card" onClick={(event) => { event.stopPropagation(); onCollection('friend') }}><div className="panel-heading"><span>🐾 いきもの図鑑</span><b>{friends.length}/{FRIEND_REWARDS.length}</b></div><div className="friend-row">{Array.from({ length: 3 }, (_, index) => { const record = friends[index]; const friend = record ? getReward(record.id) : undefined; return friend ? <div className="friend" key={friend.id}><RewardVisual reward={friend} /><small>×{record.count}</small></div> : <div className="friend locked" key={`friend-empty-${index}`}><span>?</span><small>未発見</small></div> })}</div><p>{creatureCount ? `これまでに ${creatureCount}回 出会ったよ` : '島を進んで、いきものを見つけよう！'}</p></button><button className="review-card panel" onClick={(event) => { event.stopPropagation(); onReview() }}><span className="review-icon">↻</span><div><strong>まちがいノート</strong><small>{mistakeCount ? `${mistakeCount}こ 復習できるよ` : 'いまは まちがいなし！'}</small></div><b>›</b></button><button className="key-stats-card panel" onClick={(event) => { event.stopPropagation(); onStats() }}><span className="key-stats-icon">⌨</span><div><strong>にがてキー分析</strong><small>{weakKey ? `いちばん苦手は「${weakKey.key}」・ミス率 ${weakKey.missRate}%` : totalKeyAttempts ? '今のところ苦手キーなし！' : '入力すると分析が始まるよ'}</small></div><b>›</b></button><button className="treasure-card panel collection-preview-card" onClick={(event) => { event.stopPropagation(); onCollection('treasure') }}><div className="panel-heading"><span>💎 お宝図鑑</span><b>{treasures.length}/{TREASURE_REWARDS.length}</b></div><div className="treasures">{Array.from({ length: 3 }, (_, index) => { const record = treasures[index]; const treasure = record ? getReward(record.id) : undefined; return treasure ? <span key={treasure.id} title={treasure.name}><RewardVisual reward={treasure} /><small>×{record.count}</small></span> : <span className="mystery" key={`treasure-empty-${index}`}>?</span> })}</div><small>{treasureCount ? `合計 ${treasureCount}こ 見つけたよ` : '宝箱を見つけると図鑑に増えるよ'}</small></button><div className="accuracy-card"><div className="accuracy-ring" style={{ '--score': `${accuracy * 3.6}deg` } as React.CSSProperties}><span>{accuracy}<small>%</small></span></div><div><small>今回のせいかくさ</small><strong>{accuracy >= 90 ? 'すばらしい！' : 'ゆっくりでOK！'}</strong></div></div></aside>
})
