import type { Mistake, PracticeMode } from '../../game/gameRunReducer'
import { LEARNING_STAGES } from '../../game/courseConfig'
import type { Grade } from '../../questions'
import type { Course, RewardDefinition } from '../../rewards'
import type { ScoreBreakdown } from '../../domain'
import { useConfirmShortcut } from '../../useConfirmShortcut'
import { RewardVisual } from './GameVisuals'

export function ReviewModal({ mistakes, onClose, onRetry }: { mistakes: Mistake[]; onClose: () => void; onRetry: () => void }) {
  return <div className="modal-backdrop" onClick={onClose}><section className="review-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><span className="modal-emoji">📓</span><h2>まちがいノート</h2><p>まちがえたキーを見て、もういちど覚えよう。</p>{mistakes.length === 0 ? <div className="empty-review">✨ まだまちがいはないよ。すごい！</div> : <div className="mistake-list">{mistakes.slice().reverse().map((item, index) => <div className="mistake-item" key={`${item.questionId}-${index}`}><span className="wrong-key">{item.actual}</span><span>→</span><span className="right-key">{item.expected}</span><p>{item.sentence}</p></div>)}</div>}<button className="primary-button" onClick={onRetry}>この問題をもう一度</button></section></div>
}

type StrongKey = { key: string; accuracy: number }
type WeakKey = { key: string; attempts: number; misses: number; missRate: number; commonWrong: string }

export function KeyStatsModal({ grade, totalAttempts, strongKeys, weakKeys, onClose, onPractice }: { grade: Grade; totalAttempts: number; strongKeys: StrongKey[]; weakKeys: WeakKey[]; onClose: () => void; onPractice: () => void }) {
  return <div className="modal-backdrop" onClick={onClose}><section className="review-modal key-stats-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><span className="modal-emoji">⌨️</span><h2>{grade}年生の キー成績</h2><p>{totalAttempts ? `これまでの ${totalAttempts}回の入力から分析したよ` : 'キーを入力すると、得意と苦手を少しずつ覚えるよ'}</p>{strongKeys.length > 0 && <div className="strong-key-summary"><span>✨ 得意なキー</span><div>{strongKeys.map((stat) => <kbd key={stat.key}>{stat.key}<small>{stat.accuracy}%</small></kbd>)}</div></div>}{weakKeys.length === 0 ? <div className="empty-review">{totalAttempts ? '✨ まだ苦手なキーはないよ。この調子！' : 'まずは冒険を始めて、いくつか文を入力してみよう！'}</div> : <div className="weak-key-list">{weakKeys.slice(0, 5).map((stat, index) => <div className="weak-key-row" key={stat.key}><span className="weak-rank">{index + 1}</span><kbd>{stat.key}</kbd><div><b>ミス率 {stat.missRate}%</b><span>{stat.attempts}回中 {stat.misses}回ミス{stat.commonWrong && `・「${stat.commonWrong}」を押しやすい`}</span><i><em style={{ width: `${stat.missRate}%` }} /></i></div></div>)}</div>}<button className="primary-button" disabled={weakKeys.length === 0} onClick={onPractice}>苦手なキーを集中練習　▶</button><small className="stats-note">記録はこの端末の中だけに保存されます</small></section></div>
}

export function RewardDiscoveryModal({ reward, score, onConfirm }: { reward: RewardDefinition; score: ScoreBreakdown | null; onConfirm: () => void }) {
  useConfirmShortcut(true, onConfirm, '.reward-discovery-modal .primary-button')
  return <div className="modal-backdrop reward-backdrop"><section className={`reward-discovery-modal ${reward.type === 'friend' ? 'animal' : 'treasure'} ${reward.rarity}`} onClick={(event) => event.stopPropagation()}><div className="reward-sparkles" aria-hidden="true">✦ <span>★</span> ✦</div><p className="eyebrow">{reward.rarity === 'rare' ? 'RARE DISCOVERY!' : reward.type === 'friend' ? 'NEW ENCOUNTER!' : 'TREASURE GET!'}</p>{reward.type === 'treasure' && <div className="found-from">✨ 道で光っていたものは…</div>}<div className="discovery-asset"><span /><RewardVisual reward={reward} /></div><h2>{reward.type === 'friend' ? <>「{reward.name}」と<br />出会った！</> : <>「{reward.name}」を<br />見つけた！</>}</h2><div className={`reward-rarity ${reward.rarity}`}>{reward.type === 'friend' ? `正確さ ${score?.accuracy}%・${score?.kpm} KPMで出会えた！` : reward.rarity === 'rare' ? `★ ステージ限定レア・確率 ${reward.chance}%` : `道で見つかる確率 ${reward.chance}%`}</div><p>{reward.type === 'friend' ? '上手なタイピングを見て、いきものが近づいてきたよ！' : '文の道を最後まで歩いて、お宝を手に入れたよ！'}</p><div className="reward-point-bonus">がんばりボーナス <b>+{reward.bonus} GP</b></div><button className="primary-button" onClick={(event) => { event.stopPropagation(); onConfirm() }}>確認して つぎへ進む　▶</button></section></div>
}

type RunKey = { key: string; attempts: number; missRate: number }

export function CourseClearModal({ practiceMode, reviewTargetKeys, fullyCompleted, grade, course, storyCompletion, chapterFinale, courseScore, runBonus, accuracy, attempts, misses, strongKeys, weakKeys, creatureCount, treasureCount, lifetimePoints, onContinue }: { practiceMode: PracticeMode; reviewTargetKeys: string[]; fullyCompleted: boolean; grade: Grade; course: Course; storyCompletion: string; chapterFinale: string; courseScore: number; runBonus: number; accuracy: number; attempts: number; misses: number; strongKeys: RunKey[]; weakKeys: RunKey[]; creatureCount: number; treasureCount: number; lifetimePoints: number; onContinue: () => void }) {
  useConfirmShortcut(true, onContinue, '.course-clear-modal .primary-button')
  return <div className="modal-backdrop course-clear-backdrop"><section className="review-modal course-clear-modal"><div className="clear-crown" aria-hidden="true">✦　🏆　✦</div><p className="eyebrow">{practiceMode === 'weak-keys' ? 'TRAINING CLEAR!' : fullyCompleted ? 'STAGE CLEAR!' : 'PRACTICE RESULT'}</p><h2>{practiceMode === 'weak-keys' ? 'にがてキー特訓 クリア！' : fullyCompleted ? `${grade}年生・ステージ${course} クリア！` : '今回の練習結果'}</h2><p>{practiceMode === 'weak-keys' ? `「${reviewTargetKeys.join('・')}」を含む問題を練習したよ` : fullyCompleted ? `${LEARNING_STAGES[course - 1].name}を踏破したよ！` : '選んだ問題からステージの最後まで練習したよ'}</p>{practiceMode === 'adventure' && fullyCompleted && <div className="story-completion"><b>📖 物語のつづき</b><p>{storyCompletion}</p>{chapterFinale && <strong>章の結末：{chapterFinale}</strong>}</div>}<div className="course-total-score"><span>今回のステージスコア</span><b>{courseScore.toLocaleString()}<small> GP</small></b><p>タイピング得点 {courseScore.toLocaleString()} ＋ 発見ボーナス {runBonus.toLocaleString()} GPを生涯ポイントへ加算</p></div><div className="course-score-grid"><div><span>せいかくさ</span><b>{accuracy}<small>%</small></b></div><div><span>入力したキー</span><b>{attempts}<small>回</small></b></div><div><span>まちがい</span><b>{misses}<small>回</small></b></div></div><div className="course-key-report"><section className="strong-keys"><span>✨ 得意なキー</span><div>{strongKeys.length ? strongKeys.map((stat) => <kbd key={stat.key}>{stat.key}<small>{stat.attempts}回正解</small></kbd>) : <small>もう少し入力すると分かるよ</small>}</div></section><section className="weak-keys"><span>🎯 間違いやすいキー</span><div>{weakKeys.length ? weakKeys.map((stat) => <kbd key={stat.key}>{stat.key}<small>ミス率 {stat.missRate}%</small></kbd>) : <small>苦手なキーはなかったよ！</small>}</div></section></div><div className="collection-summary"><span>これまでの発見</span><b>🐾 {creatureCount}回　💎 {treasureCount}こ　✨ {lifetimePoints.toLocaleString()} GP</b></div><button className="primary-button" onClick={onContinue}>{practiceMode === 'weak-keys' ? '通常のぼうけんへ戻る' : !fullyCompleted ? '問題一覧へ戻る' : course < LEARNING_STAGES.length ? `ステージ${course + 1}へ進む　▶` : 'ステージ選択へ戻る'}</button></section></div>
}
