import type { Mistake, PracticeMode } from '../../game/gameRunReducer'
import { LEARNING_STAGES } from '../../game/courseConfig'
import type { Grade } from '../../questions'
import type { Course, RewardDefinition } from '../../rewards'
import type { ScoreBreakdown } from '../../domain'
import { useConfirmShortcut } from '../../useConfirmShortcut'
import { RewardVisual } from './GameVisuals'
import { UIRuby } from '../UIRuby'

export function ReviewModal({ mistakes, onClose, onRetry }: { mistakes: Mistake[]; onClose: () => void; onRetry: () => void }) {
  return <div className="modal-backdrop" onClick={onClose}><section className="review-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><span className="modal-emoji">📓</span><h2>まちがいノート</h2><p>まちがえたキーを<UIRuby>見て</UIRuby>、もういちど<UIRuby>覚えよう</UIRuby>。</p>{mistakes.length === 0 ? <div className="empty-review">✨ まだまちがいはないよ。すごい！</div> : <div className="mistake-list">{mistakes.slice().reverse().map((item, index) => <div className="mistake-item" key={`${item.questionId}-${index}`}><span className="wrong-key">{item.actual}</span><span>→</span><span className="right-key">{item.expected}</span><p>{item.sentence}</p></div>)}</div>}<button className="primary-button" onClick={onRetry}>この<UIRuby>問題</UIRuby>をもう<UIRuby>一度</UIRuby></button></section></div>
}

type StrongKey = { key: string; accuracy: number }
type WeakKey = { key: string; attempts: number; misses: number; missRate: number; commonWrong: string }

export function KeyStatsModal({ grade, totalAttempts, strongKeys, weakKeys, onClose, onPractice }: { grade: Grade; totalAttempts: number; strongKeys: StrongKey[]; weakKeys: WeakKey[]; onClose: () => void; onPractice: () => void }) {
  return <div className="modal-backdrop" onClick={onClose}><section className="review-modal key-stats-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><span className="modal-emoji">⌨️</span><h2><UIRuby>{`${grade}年生の キー成績`}</UIRuby></h2><p><UIRuby>{totalAttempts ? `これまでの ${totalAttempts}回の入力から分析したよ` : 'キーを入力すると、得意と苦手を少しずつ覚えるよ'}</UIRuby></p>{strongKeys.length > 0 && <div className="strong-key-summary"><span>✨ <UIRuby>得意なキー</UIRuby></span><div>{strongKeys.map((stat) => <kbd key={stat.key}>{stat.key}<small>{stat.accuracy}%</small></kbd>)}</div></div>}{weakKeys.length === 0 ? <div className="empty-review"><UIRuby>{totalAttempts ? '✨ まだ苦手なキーはないよ。この調子！' : 'まずは冒険を始めて、いくつか文を入力してみよう！'}</UIRuby></div> : <div className="weak-key-list">{weakKeys.slice(0, 5).map((stat, index) => <div className="weak-key-row" key={stat.key}><span className="weak-rank">{index + 1}</span><kbd>{stat.key}</kbd><div><b><UIRuby>ミス率</UIRuby> {stat.missRate}%</b><span>{stat.attempts}<UIRuby>回中</UIRuby> {stat.misses}<UIRuby>回</UIRuby>ミス{stat.commonWrong && <>・「{stat.commonWrong}」を<UIRuby>押しやすい</UIRuby></>}</span><i><em style={{ width: `${stat.missRate}%` }} /></i></div></div>)}</div>}<button className="primary-button" disabled={weakKeys.length === 0} onClick={onPractice}><UIRuby>苦手なキーを集中練習</UIRuby>　▶</button><small className="stats-note"><UIRuby>記録はこの端末の中だけに保存されます</UIRuby></small></section></div>
}

export function RewardDiscoveryModal({ reward, score, onConfirm }: { reward: RewardDefinition; score: ScoreBreakdown | null; onConfirm: () => void }) {
  useConfirmShortcut(true, onConfirm, '.reward-discovery-modal .primary-button')
  return <div className="modal-backdrop reward-backdrop"><section className={`reward-discovery-modal ${reward.type === 'friend' ? 'animal' : 'treasure'} ${reward.rarity}`} onClick={(event) => event.stopPropagation()}><div className="reward-sparkles" aria-hidden="true">✦ <span>★</span> ✦</div><p className="eyebrow">{reward.rarity === 'rare' ? 'RARE DISCOVERY!' : reward.type === 'friend' ? 'NEW ENCOUNTER!' : 'TREASURE GET!'}</p>{reward.type === 'treasure' && <div className="found-from">✨ <UIRuby>道で光っていたものは</UIRuby>…</div>}<div className="discovery-asset"><span /><RewardVisual reward={reward} /></div><h2>「{reward.name}」と<br /><UIRuby>{reward.type === 'friend' ? '出会った！' : '見つけた！'}</UIRuby></h2><div className={`reward-rarity ${reward.rarity}`}><UIRuby>{reward.type === 'friend' ? `正確さ ${score?.accuracy}%・${score?.kpm} KPMで出会えた！` : reward.rarity === 'rare' ? `★ ステージ限定レア・確率 ${reward.chance}%` : `道で見つかる確率 ${reward.chance}%`}</UIRuby></div><p><UIRuby>{reward.type === 'friend' ? '上手なタイピングを見て、いきものが近づいてきたよ！' : '文の道を最後まで歩いて、お宝を手に入れたよ！'}</UIRuby></p><div className="reward-point-bonus">がんばりボーナス <b>+{reward.bonus} GP</b></div><button className="primary-button" onClick={(event) => { event.stopPropagation(); onConfirm() }}><UIRuby>確認して つぎへ進む</UIRuby>　▶</button></section></div>
}

type RunKey = { key: string; attempts: number; missRate: number }

export function CourseClearModal({ practiceMode, reviewTargetKeys, segmentClear = false, segmentNumber = 1, segmentCount = 1, fullyCompleted, grade, course, storyCompletion, chapterFinale, courseScore, runBonus, accuracy, attempts, misses, strongKeys, weakKeys, creatureCount, treasureCount, lifetimePoints, onContinue }: { practiceMode: PracticeMode; reviewTargetKeys: string[]; segmentClear?: boolean; segmentNumber?: number; segmentCount?: number; fullyCompleted: boolean; grade: Grade; course: Course; storyCompletion: string; chapterFinale: string; courseScore: number; runBonus: number; accuracy: number; attempts: number; misses: number; strongKeys: RunKey[]; weakKeys: RunKey[]; creatureCount: number; treasureCount: number; lifetimePoints: number; onContinue: () => void }) {
  useConfirmShortcut(true, onContinue, '.course-clear-modal .primary-button')
  const actionLabel = practiceMode === 'weak-keys'
    ? '通常のぼうけんへ戻る'
    : segmentClear
      ? '次のコースへ　▶'
    : !fullyCompleted
      ? '問題一覧へ戻る'
      : course < LEARNING_STAGES.length
        ? '次のステージへ　▶'
        : 'ステージ選択へ戻る'
  return <div className="modal-backdrop course-clear-backdrop"><section className="review-modal course-clear-modal" role="dialog" aria-modal="true" aria-labelledby="course-clear-title"><div className="course-clear-content"><div className="clear-crown" aria-hidden="true">✦　🏆　✦</div><p className="eyebrow">{practiceMode === 'weak-keys' ? 'TRAINING CLEAR!' : segmentClear ? 'COURSE CLEAR!' : fullyCompleted ? 'STAGE CLEAR!' : 'PRACTICE RESULT'}</p><h2 id="course-clear-title"><UIRuby>{practiceMode === 'weak-keys' ? 'にがてキー特訓 クリア！' : segmentClear ? `コース ${segmentNumber}/${segmentCount} クリア！` : fullyCompleted ? `${grade}年生・ステージ${course} クリア！` : '今回の練習結果'}</UIRuby></h2><p><UIRuby>{practiceMode === 'weak-keys' ? `「${reviewTargetKeys.join('・')}」を含む問題を練習したよ` : segmentClear ? '旅はまだ続くよ。次のコースへ進もう！' : fullyCompleted ? `${LEARNING_STAGES[course - 1].name}を踏破したよ！` : '選んだ問題からステージの最後まで練習したよ'}</UIRuby></p>{practiceMode === 'adventure' && fullyCompleted && !segmentClear && <div className="story-completion"><b>📖 <UIRuby>物語</UIRuby>のつづき</b><p>{storyCompletion}</p>{chapterFinale && <strong><UIRuby>章の結末</UIRuby>：{chapterFinale}</strong>}</div>}<div className="course-total-score"><span><UIRuby>今回のステージスコア</UIRuby></span><b>{courseScore.toLocaleString()}<small> GP</small></b><p><UIRuby>タイピング</UIRuby> {courseScore.toLocaleString()} ＋ <UIRuby>発見</UIRuby> {runBonus.toLocaleString()} GP</p></div><div className="course-score-grid"><div><span>せいかくさ</span><b>{accuracy}<small>%</small></b></div><div><span><UIRuby>入力したキー</UIRuby></span><b>{attempts}<small><UIRuby>回</UIRuby></small></b></div><div><span>まちがい</span><b>{misses}<small><UIRuby>回</UIRuby></small></b></div></div><div className="course-key-report"><section className="strong-keys"><span>✨ <UIRuby>得意なキー</UIRuby></span><div>{strongKeys.length ? strongKeys.map((stat) => <kbd key={stat.key}>{stat.key}<small>{stat.attempts}<UIRuby>回正解</UIRuby></small></kbd>) : <small>もう<UIRuby>少し入力</UIRuby>すると<UIRuby>分かる</UIRuby>よ</small>}</div></section><section className="weak-keys"><span>🎯 <UIRuby>間違いやすいキー</UIRuby></span><div>{weakKeys.length ? weakKeys.map((stat) => <kbd key={stat.key}>{stat.key}<small><UIRuby>ミス率</UIRuby> {stat.missRate}%</small></kbd>) : <small><UIRuby>苦手</UIRuby>なキーはなかったよ！</small>}</div></section></div><div className="collection-summary"><span>これまでの<UIRuby>発見</UIRuby></span><b>🐾 {creatureCount}<UIRuby>回</UIRuby>　💎 {treasureCount}こ　✨ {lifetimePoints.toLocaleString()} GP</b></div></div><footer className="course-clear-actions"><button className="primary-button" aria-keyshortcuts="Space" onClick={onContinue}><UIRuby>{actionLabel}</UIRuby></button><small className="confirm-shortcut-hint"><kbd>Space</kbd> キーでも<UIRuby>進める</UIRuby></small></footer></section></div>
}
