import type { CharacterStyle, UserProfile } from '../domain'
import { Explorer } from '../components/game/GameVisuals'
import { GRADE_OPTIONS, LEARNING_STAGES, TITLE_ISLANDS } from '../game/courseConfig'
import type { Grade } from '../questions'
import { COURSE_THEMES, getReward, type Course } from '../rewards'
import type { getAdventureRank } from '../ranks'
import type { ReturnTypeOfGoalProgress } from '../types'

export function TitlePage({ profile, grade, course, character, points, rank, soundOn, transition, completedCourses, goalProgress, tutorialComplete, onSound, onProfiles, onRomaji, onGrade, onCourse, onCharacter, onStart, onCatalog, onCollection, onRankGuide, onReport }: { profile: UserProfile; grade: Grade; course: Course; character: CharacterStyle; points: number; rank: ReturnType<typeof getAdventureRank>; soundOn: boolean; transition: 'next' | 'prev' | null; completedCourses: string[]; goalProgress: ReturnTypeOfGoalProgress; tutorialComplete: boolean; onSound: () => void; onProfiles: () => void; onRomaji: () => void; onGrade: (grade: Grade) => void; onCourse: (course: Course) => void; onCharacter: (character: CharacterStyle) => void; onStart: () => void; onCatalog: () => void; onCollection: () => void; onRankGuide: () => void; onReport: () => void }) {
  const island = TITLE_ISLANDS[grade]
  return <main className={`title-screen title-grade-${grade}`}>
    <div className="title-sky" aria-hidden="true"><span className="cloud cloud-one">☁</span><span className="cloud cloud-two">☁</span><span className="sun">☀</span></div>
    <button className="title-sound" onClick={onSound} aria-label={soundOn ? '音を消す' : '音を出す'}>{soundOn ? '♪' : '×'}</button>
    <button className="title-profile-button" onClick={onProfiles}><span>{character === 'girl' ? '👧' : '👦'}</span><div><b>{profile.name}</b><small>{rank.icon} {rank.name}</small></div><em>きりかえ ›</em></button>
    <section className="title-content"><div className="title-badge">⌨　ローマ字 × 漢字 × ぼうけん</div><div className="game-logo"><span className="logo-kicker">めざせ！ 伝説のタイピング名人</span><h1><span>ことば島</span><small>の</small><br />大ぼうけん</h1><div className="logo-stars">★　★　★</div></div>
      <div className={`title-island ${transition ?? 'settled'}`} key={grade} aria-hidden="true"><div className="island-back">{island.back}</div><div className="island-main">{island.main}</div><span className="title-friend fox">{island.friend}</span><span className="title-friend bird">🐤</span><span className="title-treasure">{island.treasure}</span><span className="spark spark-one">✦</span><span className="spark spark-two">✦</span></div>
      {transition && <div className={`title-voyage ${transition}`} aria-hidden="true"><span>⛵</span><i>〰 〰 〰</i></div>}
      <div className="start-card"><button className={`romaji-island-entry ${tutorialComplete ? 'complete' : ''}`} onClick={onRomaji}><span>{tutorialComplete ? '✓' : 'あ'}</span><div><small>{tutorialComplete ? 'いつでも おさらいできるよ' : 'はじめての人は ここから'}</small><b>ローマ字の島で 1文字れんしゅう</b><em>{tutorialComplete ? 'チュートリアル クリア！' : '清音をクリアすると本編へ進めるよ'}</em></div><strong>▶</strong></button><div className="goal-strip"><span>🔥 {goalProgress.streak}日れんぞく</span><b>今日 {goalProgress.todayProblems}/{goalProgress.dailyGoal}問・7日 {goalProgress.weeklyProblems}/{goalProgress.weeklyGoal}問</b><i><em style={{ width: `${Math.min(100, goalProgress.todayProblems / goalProgress.dailyGoal * 100)}%` }} /></i></div><p><b>{island.name}</b>へ ぼうけんする？</p><div className="lifetime-score-title"><span>{rank.icon} {rank.name}</span><b>{points.toLocaleString()}<small> GP</small></b></div>
        <div className="title-grade-switch" aria-label="学年を選ぶ">{GRADE_OPTIONS.map((value) => <button key={value} className={grade === value ? 'active' : ''} onClick={() => onGrade(value)}><b>{value}</b><span>年生</span></button>)}</div>
        <div className="title-course-switch" aria-label="コースを選ぶ">{LEARNING_STAGES.map((entry, index) => { const courseNumber = (index + 1) as Course; const isComplete = completedCourses.includes(`${grade}-${courseNumber}`); return <button key={entry.name} className={course === courseNumber ? 'active' : ''} onClick={() => onCourse(courseNumber)}><span>{isComplete ? '✓' : entry.icon}</span><b>コース {courseNumber}</b><small>{entry.habitat}</small></button> })}</div>
        <div className="course-encounter-preview"><div><span>{COURSE_THEMES[course].icon}</span><p><b>{COURSE_THEMES[course].habitat}</b><small>{COURSE_THEMES[course].description}</small></p></div><section><small>出会いやすい いきもの</small><div>{COURSE_THEMES[course].commonFriendIds.map((id) => { const creature = getReward(id); return creature ? <span key={id} title={creature.name}>{creature.icon}</span> : null })}<em title="この学年・コースだけのレア">★</em></div></section></div>
        <div className="character-picker"><span>ぼうけんしゃを えらぼう</span><div><button className={character === 'girl' ? 'active' : ''} onClick={() => onCharacter('girl')} aria-label="女の子のミナを選ぶ"><span className="character-preview"><Explorer variant="girl" /></span><b>ミナ</b><small>女の子</small></button><button className={character === 'boy' ? 'active' : ''} onClick={() => onCharacter('boy')} aria-label="男の子のソラを選ぶ"><span className="character-preview"><Explorer variant="boy" /></span><b>ソラ</b><small>男の子</small></button></div></div>
        <button className="start-button" onClick={onStart}><span>コース {course}を はじめる</span><b>▶</b></button><button className="title-catalog-button" onClick={onCatalog}>📚 コース・問題一覧と学習記録</button><button className="title-catalog-button" onClick={onCollection}>🗺️ お宝・いきもの図鑑</button><button className="title-catalog-button rank-guide-link" onClick={onRankGuide}>🏅 グレードの上がりかた</button><button className="title-catalog-button parent-report-link" onClick={onReport}>📈 保護者向け 成長レポート</button><small>まちがえても大丈夫。いきものたちと楽しくおぼえよう！</small>
      </div>
    </section><div className="title-waves" aria-hidden="true"><span>〰　〰　〰　〰　〰　〰　〰</span></div>
  </main>
}
